(function(){'use strict';
var $=function(id){return document.getElementById(id)};var trades=[],ws=null,weeklyData=null;var MAX=250000;
function fmt(n,d){if(n==null||!isFinite(n))return 'n/a';return Number(n).toLocaleString(undefined,{maximumFractionDigits:d==null?2:d})}
function jst(ms){return new Intl.DateTimeFormat('ja-JP',{timeZone:'Asia/Tokyo',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date(ms))}
function setStatus(s){$('status').textContent=s}
async function fetchJson(url){var c=new AbortController(),t=setTimeout(function(){c.abort()},12000);try{var r=await fetch(url,{signal:c.signal,cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status);return await r.json()}finally{clearTimeout(t)}}
async function seed(){var sym=$('symbol').value;var bases=['https://fapi.binance.com','https://fapi1.binance.com','https://fapi2.binance.com'];var lastErr=null;for(var i=0;i<bases.length;i++){try{var arr=await fetchJson(bases[i]+'/fapi/v1/aggTrades?symbol='+sym+'&limit=1000');trades=arr.map(norm).filter(Boolean);setStatus('Seeded '+trades.length+' recent aggregate events from '+bases[i]+'. Opening WebSocket...');render();return true}catch(e){lastErr=e}}throw lastErr||new Error('No Binance REST endpoint reachable')}
function norm(x){var id=Number(x.a),t=Number(x.T),p=Number(x.p),q=Number(x.q),m=!!x.m;if(!Number.isSafeInteger(id)||!isFinite(t)||!isFinite(p)||!isFinite(q)||q<=0)return null;return{id:id,t:t,p:p,q:q,m:m}}
function add(x){var tr=norm(x);if(!tr)return;if(trades.length&&tr.id<=trades[trades.length-1].id){return}trades.push(tr);var cutoff=Date.now()-12*3600000;while(trades.length&&trades[0].t<cutoff)trades.shift();if(trades.length>MAX)trades.splice(0,trades.length-MAX)}
async function connect(){disconnect();$('liveBadge').textContent='CONNECTING';try{await seed()}catch(e){$('liveBadge').textContent='REST FAILED';setStatus('Binance REST seed failed: '+e.message+'. Trying WebSocket anyway.')}var sym=$('symbol').value.toLowerCase();try{ws=new WebSocket('wss://fstream.binance.com/ws/'+sym+'@aggTrade');ws.onopen=function(){$('liveBadge').textContent='LIVE';setStatus('Live WebSocket connected. The chart retains only data actually captured in this tab.');};ws.onmessage=function(ev){try{add(JSON.parse(ev.data));if(trades.length%25===0)render()}catch(e){}};ws.onerror=function(){$('liveBadge').textContent='WS ERROR'};ws.onclose=function(){if($('liveBadge').textContent==='LIVE')$('liveBadge').textContent='CLOSED'};}catch(e){$('liveBadge').textContent='WS FAILED';setStatus('WebSocket failed: '+e.message)}}
function disconnect(){if(ws){try{ws.close()}catch(e){}ws=null}$('liveBadge').textContent='DISCONNECTED'}
function selected(){if(!trades.length)return[];var w=Number($('window').value),end=trades[trades.length-1].t,start=end-w;return trades.filter(function(x){return x.t>=start})}
function analyze(list,row,interval){var bins=new Map(),cols=new Map(),cv=[],sum=0;list.forEach(function(t){var k=Math.floor(t.p/row)*row,b=bins.get(k)||{buy:0,sell:0,n:0};if(t.m)b.sell+=t.q;else b.buy+=t.q;b.n++;bins.set(k,b);var c=Math.floor(t.t/interval)*interval,cm=cols.get(c)||new Map(),cb=cm.get(k)||{buy:0,sell:0};if(t.m)cb.sell+=t.q;else cb.buy+=t.q;cm.set(k,cb);cols.set(c,cm);sum+=t.m?-t.q:t.q;cv.push([t.t,sum]);});var rows=[...bins.entries()].sort(function(a,b){return a[0]-b[0]});var poc=null,mx=-1;rows.forEach(function(r){var v=r[1].buy+r[1].sell;if(v>mx){mx=v;poc=r[0]+row/2}});return{rows:rows,cols:cols,cv:cv,poc:poc,delta:sum}}
function svgLine(points,title){if(!points.length)return '<div class="notice">No data.</div>';var W=1200,H=270,L=70,R=1180,T=40,B=225;var xs=points.map(function(p){return p[0]}),ys=points.map(function(p){return p[1]});var xmin=Math.min.apply(null,xs),xmax=Math.max.apply(null,xs),ymin=Math.min(0,Math.min.apply(null,ys)),ymax=Math.max(0,Math.max.apply(null,ys));if(ymax===ymin){ymax=ymin+1}var x=function(v){return L+(v-xmin)/(xmax-xmin||1)*(R-L)},y=function(v){return B-(v-ymin)/(ymax-ymin)*(B-T)};var d=points.map(function(p,i){return(i?'L':'M')+x(p[0]).toFixed(1)+' '+y(p[1]).toFixed(1)}).join(' ');return '<svg viewBox="0 0 '+W+' '+H+'"><text x="70" y="24" font-size="12" font-weight="600">'+title+'</text><line x1="70" y1="'+y(0)+'" x2="1180" y2="'+y(0)+'" stroke="#aaa"/><path d="'+d+'" fill="none" stroke="#111" stroke-width="1.4"/><text x="70" y="255" font-size="10">'+jst(xmin)+' JST</text><text x="1080" y="255" font-size="10">'+jst(xmax)+' JST</text></svg>'}
function profileSvg(rows,row,title){if(!rows.length)return '<div class="notice">No data.</div>';var W=1200,H=Math.min(700,Math.max(260,rows.length*9+70)),L=90,R=1160,T=35,B=H-30;var max=Math.max.apply(null,rows.map(function(r){return r[1].buy+r[1].sell}));var rh=(B-T)/rows.length;var s='<svg viewBox="0 0 '+W+' '+H+'"><text x="90" y="22" font-size="12" font-weight="600">'+title+'</text>';rows.forEach(function(r,i){var y=B-(i+1)*rh,bw=(r[1].buy/max)*(R-L),sw=(r[1].sell/max)*(R-L);s+='<rect x="'+L+'" y="'+y+'" width="'+sw+'" height="'+Math.max(1,rh-1)+'" fill="#f0caca"/><rect x="'+(L+sw)+'" y="'+y+'" width="'+bw+'" height="'+Math.max(1,rh-1)+'" fill="#cce8d2"/><text x="6" y="'+(y+rh*.72)+'" font-size="9">'+fmt(r[0]+row/2,1)+'</text>'});return s+'</svg>'}
function footprintHtml(cols,row){var times=[...cols.keys()].sort(function(a,b){return a-b});if(!times.length)return '<div class="notice">No footprint data.</div>';times=times.slice(-20);var priceSet=new Set();times.forEach(function(t){cols.get(t).forEach(function(v,k){priceSet.add(k)})});var prices=[...priceSet].sort(function(a,b){return b-a}).slice(0,80);var h='<table class="fpTable"><thead><tr><th>Price</th>';times.forEach(function(t){h+='<th colspan="2">'+jst(t).split(' ')[1]+'</th>'});h+='</tr><tr><th></th>';times.forEach(function(){h+='<th>Bid</th><th>Ask</th>'});h+='</tr></thead><tbody>';prices.forEach(function(p){h+='<tr><td class="price">'+fmt(p+row/2,1)+'</td>';times.forEach(function(t){var b=cols.get(t).get(p)||{buy:0,sell:0};h+='<td class="sell">'+fmt(b.sell,3)+'</td><td class="buy">'+fmt(b.buy,3)+'</td>'});h+='</tr>'});return h+'</tbody></table>'}
function render(){var list=selected(),row=Number($('row').value)||10,interval=Number($('interval').value)||15000;if(!list.length){$('coverage').textContent='No captured flow.';return}var a=analyze(list,row,interval),first=list[0],last=list[list.length-1];$('last').textContent=fmt(last.p,1);$('cvd').textContent=(a.delta>=0?'+':'')+fmt(a.delta,3);$('poc').textContent=fmt(a.poc,1);$('count').textContent=fmt(list.length,0);$('coverage').textContent='Actual captured coverage: '+jst(first.t)+' to '+jst(last.t)+' JST ('+fmt((last.t-first.t)/60000,2)+' min). Requested window is '+fmt(Number($('window').value)/3600000,2)+' h.';$('profile').innerHTML=profileSvg(a.rows,row,'CAPTURED VP / sell + buy');$('footprint').innerHTML=footprintHtml(a.cols,row);$('cvdChart').innerHTML=svgLine(a.cv,'CVD / BTC / captured aggregate events')}
function rebinWeekly(rows,size){var m=new Map();rows.forEach(function(r){var k=Math.floor(Number(r[0])/size)*size,b=m.get(k)||{buy:0,sell:0};b.buy+=Number(r[1]);b.sell+=Number(r[2]);m.set(k,b)});return[...m.entries()].sort(function(a,b){return a[0]-b[0]})}
async function loadWeekly(){try{weeklyData=await fetchJson('weekly-vp.json?ts='+Date.now());renderWeekly()}catch(e){$('weeklyStatus').textContent='Weekly archive file not available yet: '+e.message+'. The live section still works.';$('weekly').innerHTML=''}}
function renderWeekly(){if(!weeklyData)return;var key=$('week').value,p=weeklyData[key];if(!p||!p.rows||!p.rows.length){$('weeklyStatus').textContent='No archived rows for '+key+'.';$('weekly').innerHTML='';return}var size=Number($('weekRow').value),rows=rebinWeekly(p.rows,size);$('weeklyStatus').textContent=p.label+' | archived UTC days: '+p.days.join(', ')+' | generated '+weeklyData.generatedAt+' | exact source: Binance Vision aggTrades, checksum verified.';$('weekly').innerHTML=profileSvg(rows,size,'WEEKLY VP / '+p.label)}
$('connect').onclick=connect;$('disconnect').onclick=disconnect;$('symbol').onchange=function(){disconnect();trades=[];render();};['window','row','interval'].forEach(function(id){$(id).onchange=render});$('weeklyReload').onclick=loadWeekly;$('week').onchange=renderWeekly;$('weekRow').onchange=renderWeekly;setInterval(function(){if(ws&&ws.readyState===1)render()},3000);loadWeekly();
})();